name: "Release"

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name  (1.2.3)'
        required: true

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v1.3.3
        env:
          SECRET_MAVEN_USERNAME: ${{ secrets.SECRET_MAVEN_USERNAME }}
          SECRET_MAVEN_PASSWORD: ${{ secrets.SECRET_MAVEN_PASSWORD }}
        with:
          arguments: clean build publish
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.versionName }}
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.versionName }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Automatic relase commits for ${{ github.event.inputs.versionName }}
          branch: master
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ github.event.inputs.versionName }}
          files: |
            LICENSE
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
